name: nop_annotations
description: nop annotations.
version: 0.2.0
repository: https://github.com/sersr/nop_annotations

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.0